# Configurations for CloudedBats WIRC-2025.
---
wirc_app:
  port: 8082
  host: "0.0.0.0"
  log_level: info

cam0:
  name: Camera-A (cam0)
  camera_mode: video
  active: true
  monochrome: false
  orientation:
    hflip: 0
    vflip: 0
  settings: 
    saturation: auto
    exposure_time_us: 1000
    analogue_gain: auto
  preview:
    size_divisor: 2.0
  video:
    horizontal_size_px: max
    framerate_fps: 30
    pre_buffer_frames: 60
    length_after_buffer_s: 4
    file_prefix: wircA
  image:
    file_prefix: wircA
  storage:
    rec_dir: /home/wurb/wirc_recordings
    remove_old_rec: true
    free_space_limit_mb: 500

cam1:
  name: Camera-B (cam1)
  camera_mode: video
  active: true
  monochrome: false
  orientation:
    hflip: 0
    vflip: 0
  settings: 
    saturation: auto
    exposure_time_us: 1000
    analogue_gain: auto
  preview:
    size_divisor: 2.0
  video:
    horizontal_size_px: max
    framerate_fps: 30
    pre_buffer_frames: 60
    length_after_buffer_s: 4
    file_prefix: wircB
  image:
    file_prefix: wircB
  storage:
    rec_dir: /home/wurb/wirc_recordings
    remove_old_rec: true
    free_space_limit_mb: 500

preview:
  horizontal_size_px: 480
  
camera_modes:
  - mode_name: Video (on demand)
    mode_value: video
  - mode_name: Video (continuous)
    mode_value: video-continuous
  - mode_name: Image (Jpeg)
    mode_value: image

client_info:
  max_log_rows: 50

# record:
#   targets:
#     - id: sda1
#       name: USB-1
#       media_path: /media/USB-sda1
#       rec_dir: wirc_recordings
#     - id: sdb1
#       name: USB-2
#       media_path: /media/USB-sdb1
#       rec_dir: wirc_recordings
#     - id: local
#       name: Local
#       rec_dir: /user/wurb/wirc_recordings
#       free_disk_limit: 500 # Unit MB.
